Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "20480" 
    vb.cpus = "8"
  end
  config.disksize.size = "150GB"
  config.vm.define :chromium_vm do |t|
  end
end
