FROM ubuntu:18.04

RUN apt-get update && apt-get install -y wget python clang llvm git lcov mercurial

RUN hg clone https://hg.mozilla.org/mozilla-unified

#RUN python /home/firefox-src/bootstrap.py  --application-choice=browser --no-interactive






